class AddKeys < ActiveRecord::Migration
  def up
      #Removing obselete data.
      execute "delete from vouchers where id IN (select id from vouchers where organization_id NOT IN (select id from organizations));"
      execute "delete from evaluations where id IN (select id from evaluations where organization_id NOT IN (select id from organizations));"
      execute "delete from equipes where id IN (select id from equipes where organization_id NOT IN (select id from organizations));"
      execute "delete from exercises where id IN (select id from exercises where organization_id not in (select id from organizations));"
      execute "delete from memberships where id in (select id from memberships where organization_id not in (select id from organizations));"
      execute "delete from memberships where id in (select id from memberships where user_id not in (select id from users));"
      execute "delete from participations where equipe_id in (select equipe_id from participations where equipe_id not in (select id from equipes));"
      execute "delete from prescriptions where eval_test_id  in (select eval_test_id from prescriptions where eval_test_id not in (select id from eval_tests));"
      execute "delete from resultats where equipe_id in (select equipe_id from resultats where equipe_id not in (select id from equipes));"
      execute "delete from resultats where evaluation_id in (select evaluation_id from resultats where evaluation_id not in (select id from evaluations));"
      execute "delete from scat2_cognitions where id in (select id from scat2_cognitions where scat2_id not in (select id from scat2s));"
      execute "delete from scat2_concentrations where id in (select id from scat2_concentrations where scat2_id not in (select id from scat2s));"
      execute "delete from scat2_memories where id in (select id from scat2_memories where scat2_id not in (select id from scat2s));"
      execute "delete from scat2_symptoms where id in (select id from scat2_symptoms where scat2_id not in (select id from scat2s));"
      execute "delete from test_sets where id in (select id from test_sets where eval_test_id not in (select id from eval_tests));"
      execute "delete from test_sets where id IN (select id from test_sets where evaluation_id NOT IN (select id from evaluations));" 


      add_foreign_key "blessures", "equipe_types", name: "blessures_equipe_type_id_fk"
      add_foreign_key "blessures", "users", column: "reporter_id", name: "blessures_reporter_id_fk"
      add_foreign_key "blessures", "users", name: "blessures_user_id_fk"
      add_foreign_key "equipe_types", "organizations", name: "equipe_types_organization_id_fk"
      add_foreign_key "equipes", "equipe_types", name: "equipes_equipe_type_id_fk"
      add_foreign_key "equipes", "organizations", name: "equipes_organization_id_fk"
      add_foreign_key "equipes", "users", name: "equipes_user_id_fk"
      add_foreign_key "eval_tests", "organizations", name: "eval_tests_organization_id_fk"
      add_foreign_key "eval_tests", "test_subcategories", name: "eval_tests_test_subcategory_id_fk"
      add_foreign_key "eval_tests", "users", name: "eval_tests_user_id_fk"
      add_foreign_key "eval_types", "organizations", name: "eval_types_organization_id_fk"
      add_foreign_key "evaluations", "eval_types", name: "evaluations_eval_type_id_fk"
      add_foreign_key "evaluations", "organizations", name: "evaluations_organization_id_fk"
      add_foreign_key "evaluations", "users", name: "evaluations_user_id_fk"
      add_foreign_key "exercise_categories", "organizations", name: "exercise_categories_organization_id_fk"
      add_foreign_key "exercise_sets", "exercises", name: "exercise_sets_exercise_id_fk"
      add_foreign_key "exercise_sets", "programmes", name: "exercise_sets_programme_id_fk"
      add_foreign_key "exercise_subcategories", "exercise_categories", name: "exercise_subcategories_exercise_category_id_fk"
      add_foreign_key "exercise_subcategories", "organizations", name: "exercise_subcategories_organization_id_fk"
      add_foreign_key "exercises", "exercise_subcategories", name: "exercises_exercise_subcategory_id_fk"
      add_foreign_key "exercises", "organizations", name: "exercises_organization_id_fk"
      add_foreign_key "exercises", "users", name: "exercises_user_id_fk"
      add_foreign_key "family_members", "users", column: "parent_id", name: "family_members_parent_id_fk"
      add_foreign_key "family_members", "users", name: "family_members_user_id_fk"
      add_foreign_key "memberships", "organizations", name: "memberships_organization_id_fk"
      add_foreign_key "memberships", "roles", name: "memberships_role_id_fk"
      add_foreign_key "memberships", "users", name: "memberships_user_id_fk"
      add_foreign_key "vouchers", "organizations", name: "organizations_voucher_id_fk"
      add_foreign_key "participations", "equipes", name: "participations_equipe_id_fk"
      add_foreign_key "participations", "positions", name: "participations_position_id_fk"
      add_foreign_key "participations", "users", name: "participations_user_id_fk"
      add_foreign_key "positions", "equipe_types", name: "positions_equipe_type_id_fk"
      add_foreign_key "positions", "organizations", name: "positions_organization_id_fk"
      add_foreign_key "prescriptions", "eval_tests", name: "prescriptions_eval_test_id_fk"
      add_foreign_key "prescriptions", "exercises", name: "prescriptions_exercise_id_fk"
      add_foreign_key "programmes", "users", name: "programmes_user_id_fk"
      add_foreign_key "resultats", "users", column: "athlete_id", name: "resultats_athlete_id_fk"
      add_foreign_key "resultats", "equipes", name: "resultats_equipe_id_fk"
      add_foreign_key "resultats", "eval_tests", name: "resultats_eval_test_id_fk"
      add_foreign_key "resultats", "evaluations", name: "resultats_evaluation_id_fk"
      add_foreign_key "resultats", "users", name: "resultats_user_id_fk"
      add_foreign_key "vouchers", "roles", name: "roles_voucher_id_fk"
      add_foreign_key "scat2_cognitions", "scat2s", name: "scat2_cognitions_scat2_id_fk"
      add_foreign_key "scat2_concentrations", "scat2s", name: "scat2_concentrations_scat2_id_fk"
      add_foreign_key "scat2_memories", "scat2s", name: "scat2_memories_scat2_id_fk"
      add_foreign_key "scat2_symptoms", "scat2s", name: "scat2_symptoms_scat2_id_fk"
      add_foreign_key "scat2s", "equipe_types", name: "scat2s_equipe_type_id_fk"
      add_foreign_key "scat2s", "users", column: "owner_id", name: "scat2s_owner_id_fk"
      add_foreign_key "scat2s", "users", name: "scat2s_user_id_fk"
      add_foreign_key "test_categories", "organizations", name: "test_categories_organization_id_fk"
      add_foreign_key "test_sets", "eval_tests", name: "test_sets_eval_test_id_fk"
      add_foreign_key "test_sets", "evaluations", name: "test_sets_evaluation_id_fk"
      add_foreign_key "test_subcategories", "organizations", name: "test_subcategories_organization_id_fk"
      add_foreign_key "test_subcategories", "test_categories", name: "test_subcategories_test_category_id_fk"
      add_foreign_key "user_anthropometrics", "users", name: "user_anthropometrics_user_id_fk"
      add_foreign_key "user_emails", "users", name: "user_emails_user_id_fk"
      add_foreign_key "user_phones", "users", name: "user_phones_user_id_fk"
      add_foreign_key "vouchers", "organizations", name: "vouchers_organization_id_fk"
      add_foreign_key "vouchers", "roles", name: "vouchers_role_id_fk"
  end

  def down
      remove_foreign_key "blessures", "equipe_types", name: "blessures_equipe_type_id_fk"
      remove_foreign_key "blessures", "blessures", column: "original_report_id", name: "blessures_original_report_id_fk"
      remove_foreign_key "blessures", "users", column: "reporter_id", name: "blessures_reporter_id_fk"
      remove_foreign_key "blessures", "users", name: "blessures_user_id_fk"
      remove_foreign_key "equipe_types", "organizations", name: "equipe_types_organization_id_fk"
      remove_foreign_key "equipes", "equipe_types", name: "equipes_equipe_type_id_fk"
      remove_foreign_key "equipes", "organizations", name: "equipes_organization_id_fk"
      remove_foreign_key "equipes", "users", name: "equipes_user_id_fk"
      remove_foreign_key "eval_tests", "organizations", name: "eval_tests_organization_id_fk"
      remove_foreign_key "eval_tests", "test_subcategories", name: "eval_tests_test_subcategory_id_fk"
      remove_foreign_key "eval_tests", "users", name: "eval_tests_user_id_fk"
      remove_foreign_key "eval_types", "organizations", name: "eval_types_organization_id_fk"
      remove_foreign_key "evaluations", "eval_types", name: "evaluations_eval_type_id_fk"
      remove_foreign_key "evaluations", "organizations", name: "evaluations_organization_id_fk"
      remove_foreign_key "evaluations", "users", name: "evaluations_user_id_fk"
      remove_foreign_key "exercise_categories", "organizations", name: "exercise_categories_organization_id_fk"
      remove_foreign_key "exercise_sets", "exercises", name: "exercise_sets_exercise_id_fk"
      remove_foreign_key "exercise_sets", "programmes", name: "exercise_sets_programme_id_fk"
      remove_foreign_key "exercise_subcategories", "exercise_categories", name: "exercise_subcategories_exercise_category_id_fk"
      remove_foreign_key "exercise_subcategories", "organizations", name: "exercise_subcategories_organization_id_fk"
      remove_foreign_key "exercises", "exercise_subcategories", name: "exercises_exercise_subcategory_id_fk"
      remove_foreign_key "exercises", "organizations", name: "exercises_organization_id_fk"
      remove_foreign_key "exercises", "users", name: "exercises_user_id_fk"
      remove_foreign_key "family_members", "users", column: "parent_id", name: "family_members_parent_id_fk"
      remove_foreign_key "family_members", "users", name: "family_members_user_id_fk"
      remove_foreign_key "memberships", "organizations", name: "memberships_organization_id_fk"
      remove_foreign_key "memberships", "roles", name: "memberships_role_id_fk"
      remove_foreign_key "memberships", "users", name: "memberships_user_id_fk"
      remove_foreign_key "organizations", "vouchers", name: "organizations_voucher_id_fk"
      remove_foreign_key "participations", "equipes", name: "participations_equipe_id_fk"
      remove_foreign_key "participations", "positions", name: "participations_position_id_fk"
      remove_foreign_key "participations", "users", name: "participations_user_id_fk"
      remove_foreign_key "positions", "equipe_types", name: "positions_equipe_type_id_fk"
      remove_foreign_key "positions", "eval_types", name: "positions_eval_type_id_fk"
      remove_foreign_key "positions", "organizations", name: "positions_organization_id_fk"
      remove_foreign_key "prescriptions", "eval_tests", name: "prescriptions_eval_test_id_fk"
      remove_foreign_key "prescriptions", "exercises", name: "prescriptions_exercise_id_fk"
      remove_foreign_key "programmes", "users", name: "programmes_user_id_fk"
      remove_foreign_key "resultats", "users", column: "athlete_id", name: "resultats_athlete_id_fk"
      remove_foreign_key "resultats", "equipes", name: "resultats_equipe_id_fk"
      remove_foreign_key "resultats", "eval_tests", name: "resultats_eval_test_id_fk"
      remove_foreign_key "resultats", "evaluations", name: "resultats_evaluation_id_fk"
      remove_foreign_key "resultats", "users", name: "resultats_user_id_fk"
      remove_foreign_key "roles", "vouchers", name: "roles_voucher_id_fk"
      remove_foreign_key "scat2_cognitions", "scat2s", name: "scat2_cognitions_scat2_id_fk"
      remove_foreign_key "scat2_concentrations", "scat2s", name: "scat2_concentrations_scat2_id_fk"
      remove_foreign_key "scat2_memories", "scat2s", name: "scat2_memories_scat2_id_fk"
      remove_foreign_key "scat2_symptoms", "scat2s", name: "scat2_symptoms_scat2_id_fk"
      remove_foreign_key "scat2s", "equipe_types", name: "scat2s_equipe_type_id_fk"
      remove_foreign_key "scat2s", "users", column: "owner_id", name: "scat2s_owner_id_fk"
      remove_foreign_key "scat2s", "users", name: "scat2s_user_id_fk"
      remove_foreign_key "test_categories", "organizations", name: "test_categories_organization_id_fk"
      remove_foreign_key "test_sets", "eval_tests", name: "test_sets_eval_test_id_fk"
      remove_foreign_key "test_sets", "evaluations", name: "test_sets_evaluation_id_fk"
      remove_foreign_key "test_subcategories", "organizations", name: "test_subcategories_organization_id_fk"
      remove_foreign_key "test_subcategories", "test_categories", name: "test_subcategories_test_category_id_fk"
      remove_foreign_key "user_anthropometrics", "users", name: "user_anthropometrics_user_id_fk"
      remove_foreign_key "user_emails", "users", name: "user_emails_user_id_fk"
      remove_foreign_key "user_phones", "users", name: "user_phones_user_id_fk"
      remove_foreign_key "vouchers", "organizations", name: "vouchers_organization_id_fk"
      remove_foreign_key "vouchers", "roles", name: "vouchers_role_id_fk"
  end

end
