require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseCategory. As you add validations to ExerciseCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all exercise_categories as @exercise_categories" do
      exercise_category = ExerciseCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_categories).should eq([exercise_category])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_category as @exercise_category" do
      exercise_category = ExerciseCategory.create! valid_attributes
      get :show, {:id => exercise_category.to_param}, valid_session
      assigns(:exercise_category).should eq(exercise_category)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_category as @exercise_category" do
      get :new, {}, valid_session
      assigns(:exercise_category).should be_a_new(ExerciseCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_category as @exercise_category" do
      exercise_category = ExerciseCategory.create! valid_attributes
      get :edit, {:id => exercise_category.to_param}, valid_session
      assigns(:exercise_category).should eq(exercise_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseCategory" do
        expect {
          post :create, {:exercise_category => valid_attributes}, valid_session
        }.to change(ExerciseCategory, :count).by(1)
      end

      it "assigns a newly created exercise_category as @exercise_category" do
        post :create, {:exercise_category => valid_attributes}, valid_session
        assigns(:exercise_category).should be_a(ExerciseCategory)
        assigns(:exercise_category).should be_persisted
      end

      it "redirects to the created exercise_category" do
        post :create, {:exercise_category => valid_attributes}, valid_session
        response.should redirect_to(ExerciseCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_category as @exercise_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCategory.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_category => {}}, valid_session
        assigns(:exercise_category).should be_a_new(ExerciseCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCategory.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_category" do
        exercise_category = ExerciseCategory.create! valid_attributes
        # Assuming there are no other exercise_categories in the database, this
        # specifies that the ExerciseCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => exercise_category.to_param, :exercise_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested exercise_category as @exercise_category" do
        exercise_category = ExerciseCategory.create! valid_attributes
        put :update, {:id => exercise_category.to_param, :exercise_category => valid_attributes}, valid_session
        assigns(:exercise_category).should eq(exercise_category)
      end

      it "redirects to the exercise_category" do
        exercise_category = ExerciseCategory.create! valid_attributes
        put :update, {:id => exercise_category.to_param, :exercise_category => valid_attributes}, valid_session
        response.should redirect_to(exercise_category)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_category as @exercise_category" do
        exercise_category = ExerciseCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_category.to_param, :exercise_category => {}}, valid_session
        assigns(:exercise_category).should eq(exercise_category)
      end

      it "re-renders the 'edit' template" do
        exercise_category = ExerciseCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_category.to_param, :exercise_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_category" do
      exercise_category = ExerciseCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_category.to_param}, valid_session
      }.to change(ExerciseCategory, :count).by(-1)
    end

    it "redirects to the exercise_categories list" do
      exercise_category = ExerciseCategory.create! valid_attributes
      delete :destroy, {:id => exercise_category.to_param}, valid_session
      response.should redirect_to(exercise_categories_url)
    end
  end

end
